language: ruby
rvm:
  - 2.2
before_install:
  - nvm install stable
  - nvm use node
  - npm install firebase
script:
  - bundle exec jekyll build
  - $(npm bin)/firebase deploy --token "$FIREBASE_API_TOKEN"
