language: ruby
rvm:
  - 2.2
before_install:
  - nvm install stable
  - nvm use node
  - npm install -g firebase
script:
  - bundle exec jekyll build
  - $(npm --global bin)/firebase-tools deploy --token "$FIREBASE_API_TOKEN"
